/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.droga_do_chodzenia;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import org.json.*;

/**
 *
 * @author michaldondajewski
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow(){
        initComponents();
        downloadDataFromDb();
        listTheTraces();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTrasy = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTrasy = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaOpisTrasy = new javax.swing.JTextArea();
        jLabelOpisTrasy = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuZapiszTraceDoPliku = new javax.swing.JMenu();
        jMenuItemZapiszTraseDoPliku = new javax.swing.JMenuItem();
        jMenuItemZamknijAplikacje = new javax.swing.JMenuItem();
        jMenuItemInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelTrasy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTrasy.setText("Trasy:");

        jScrollPane1.setViewportView(jListTrasy);

        jTextAreaOpisTrasy.setEditable(false);
        jTextAreaOpisTrasy.setColumns(20);
        jTextAreaOpisTrasy.setRows(5);
        jScrollPane2.setViewportView(jTextAreaOpisTrasy);

        jLabelOpisTrasy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelOpisTrasy.setText("Opis trasy: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTrasy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelOpisTrasy)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrasy)
                    .addComponent(jLabelOpisTrasy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenuZapiszTraceDoPliku.setText("Plik");

        jMenuItemZapiszTraseDoPliku.setText("Zapisz Trase Do Pliku");
        jMenuZapiszTraceDoPliku.add(jMenuItemZapiszTraseDoPliku);

        jMenuItemZamknijAplikacje.setText("Zamknij aplikacje");
        jMenuZapiszTraceDoPliku.add(jMenuItemZamknijAplikacje);

        jMenuItemInfo.setText("O Aplikacji");
        jMenuZapiszTraceDoPliku.add(jMenuItemInfo);

        jMenuBar1.add(jMenuZapiszTraceDoPliku);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    String jsonText;
    DefaultListModel<String> model = new DefaultListModel<>();
    ArrayList<String> jsonObjectsList = new ArrayList<String>();
    
    public void downloadDataFromDb(){
        String url = "https://my-json-server.typicode.com/M66D22/Droga_do_chodzenia/db";
        InputStream is = null;
        try {
            is = new URL(url).openStream(); //otwarcie połączenia
            BufferedReader rd = new BufferedReader(new InputStreamReader(is, Charset.forName("UTF-8")));
            StringBuilder sb = new StringBuilder();
            int cp;
            while((cp = rd.read()) != -1){
                sb.append((char) cp);
            }
            jsonText = sb.toString();
            is.close();
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException e){
            e.printStackTrace();
        }
    }
    
    //Dodać jsonObjectClass do listy którą muszę stworzyć
    public void listTheTraces(){
        JSONObject obj = new JSONObject(jsonText);
        JSONArray routes = obj.getJSONArray("routes");
        for (int i=0; i<routes.length(); i++){   
            String name = routes.getJSONObject(i).getString("name");
            model.addElement(name);
            
            int length = routes.getJSONObject(i).getInt("length");
            
            String description = routes.getJSONObject(i).getString("description");
            
            String type = routes.getJSONObject(i).getString("type");
            
            JsonObjectClass jsonObjectClass = new JsonObjectClass(i, name, length, description, type);
            //System.out.println(jsonObjectClass.toString());
            jsonObjectsList.add(jsonObjectClass.toString());
        }
        jListTrasy.setModel(model);
        System.out.println(jsonObjectsList);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelOpisTrasy;
    private javax.swing.JLabel jLabelTrasy;
    private javax.swing.JList<String> jListTrasy;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemInfo;
    private javax.swing.JMenuItem jMenuItemZamknijAplikacje;
    private javax.swing.JMenuItem jMenuItemZapiszTraseDoPliku;
    private javax.swing.JMenu jMenuZapiszTraceDoPliku;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaOpisTrasy;
    // End of variables declaration//GEN-END:variables
}
